language: sh

matrix:
    include:
        - os: linux
          env: PYENV=py36
        - os: linux
          env: PYENV=py37
# There is a new error only on mac py36, turning off for now. It is:
# ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
#        - os: osx
#          env: PYENV=py36
        - os: osx
          env: PYENV=py37
# Observed on 10-Feb-19, choclatey builds for miniconda3 break
# see: https://github.com/conda/conda/issues/6064
# It is not clear how/when this can be fixed, so turn this back off for now
#        - os: windows
#          env: PYENV=py37
# there is no maintained miniconda2 package for chocolatey
#        - os: windows
#          env: PYENV=py27

before_install:
  - source ./ci/env.sh
  - bash ./ci/travis-install-miniconda.sh
  - conda create -n testing python=$PYVERSION --yes
  - source activate testing
  # I found this to be necessary because of failures in default enviornment pip like:
  # ModuleNotFoundError: No module named 'pip._internal.main'
  - python -m pip install --upgrade pip
  - make -B virtual-environment

install:
  - make install

script:
  - conda list
  - python -c "import os; print(os.environ['PYVERSION'])"
  - python -c "import sys; print(sys.version)"
  - python -c "import os, sys; assert os.environ['PYVERSION'] == '.'.join([sys.version[0], sys.version[2]])"
  - make test
  - cd doc
  - if [[ "${PYENV}" == "py37" && "${TRAVIS_OS_NAME}" != 'windows' ]]; then make html; fi
  - cd ..

after_success:
  - cd tests && coveralls
